replicaCount: 1
image:
  repository: romuloass/pucpratica2k8s
  tag: frontendapp
service:
  type: ClusterIP
  port: 8080
livenessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 5
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: true
  host: pucpratica2k8s.com

backend:
  service:
    name: backendapp
    port: 5000

