frontend:
  enabled: true
  replicacount: 1
  image:
    repository: frontend
    tag: latest
  service:
    type: ClusterIP
    port: 80

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: backend
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

database:
  enabled: true
  image:
    repository: postgres
    tag: 16
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 1Gi
  secrets:
    postgres:
      user: myuser
      password: mypassword
      database: mydb

ingress:
  enabled: true
  host: myapp.local


  # This is to override the chart name.
nameOverride: ""
fullnameOverride: ""