image:
  repository: postgres
  tag: 13
service:
  type: ClusterIP
  port: 5432
persistence:
  enabled: true
  size: 1Gi
secrets:
  postgres:
    user: myuser
    password: mypassword
    database: mydb