apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc }}
  PGUSER: {{ .Values.secrets.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.secrets.postgres.database | b64enc }}