image:
  repository: postgres
  tag: 17.0-alpine
service:
  type: ClusterIP
  port: 5432
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Mi
secrets:
  postgres:
    user: postgres
    password: secretpass
    database: postgres
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 15
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi