replicaCount: 1
image:
  repository: romuloass/pucpratica2k8s
  tag: backendapp
service:
  type: ClusterIP
  port: 5000
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
database:
  service:
    name: postgresdb
secrets:
  postgres:
    user: postgres
    password: secretpass
    database: postgres