apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-configmap
data:
    FLASK_APP: "run.py"
    FLASK_DB_TYPE: "postgres"
    FLASK_DB_PORT: "5432"
    FLASK_DB_HOST: "{{ printf "%s-%s-%s" .Release.Name .Values.database.service.name "database" | trunc 63 | trimSuffix "-" }}"
    FLASK_ENV: "production"