apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
type: Opaque
data:
  FLASK_DB_USER: {{ .Values.secrets.postgres.user | b64enc }}
  FLASK_DB_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  FLASK_DB_NAME: {{ .Values.secrets.postgres.database | b64enc }}